services:
  db:
    image: postgres
    container_name: banner-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banner-keeper
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "postgresql://postgres:password@db:5432/banner-keeper?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations

  cache:
    image: redis
    container_name: banner-cache
    environment:
      REDIS_PASSWORD: redis-password
      REDIS_PORT: 6379
      REDIS_DATABASES: 0
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: banner-app
    build: .
    environment:
      POSTGRES_DSN: postgresql://postgres:password@db:5432/banner-keeper
      REDIS_URL: redis://default:redis-password@banner-cache:6379/0
      REDIS_EXPIRATION_DURATION: 5m
      JWT_PRIVATE_KEY: secret-key
      LOG_LEVEL: info
    depends_on:
      migrate:
        condition: service_completed_successfully
      cache:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ./banner-service
volumes:
  data: