services:
  db-test:
    image: postgres
    container_name: test-banner-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banner-keeper
    ports:
      - "6500:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test-data:/var/lib/postgresql/data

  cache-test:
    image: redis
    container_name: test-banner-cache
    environment:
      - REDIS_PASSWORD=redis-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate-test:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "postgresql://postgres:password@db-test:5432/banner-keeper?sslmode=disable", "up" ]
    depends_on:
      db-test:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
volumes:
  test-data: